### ISSUE TITLE
leaking message contents

### ISSUE THREAD

**Issue by yosemitebandit** [endaga/smqueue#11]
from syslog:

`Jun 10 18:31:44 endaga smqueue: NOTICE 1132:1173 2015-06-10T18:31:44.2 smqueue.h:505:get_text: Decoded text: Your account doesn't have sufficient funds.`

**Comment by shaddi** [comment]
Fixed in client.

**Comment by kheimerl** [comment]
Likely still happens in smq

**Comment by kheimerl** [comment]
I guess that's an smq issue.
