### ISSUE TITLE
No stable storage of messages:

### ISSUE THREAD

**Issue by kheimerl** [endaga/smqueue#15]
INSERT INTO "CONFIG" VALUES('SubscriberRegistry.db','/var/lib/asterisk/sqlite3dir/sqlite3.db',0,0,'The location of the sqlite3 database holding the subscriber registry.');
INSERT INTO "CONFIG" VALUES('savefile','/tmp/save',0,0,'The file to save SMS messages to when exiting.');

We only save them on shutdown I think. Need a mechanism for holding onto them through power cycles.

**Comment by kkroo** [comment]
Just save them under `/etc/OpenBTS/`? Does it check that config path each load?

**Comment by kheimerl** [comment]
There's a formatting bit and a repeat messages bit that needs to be figured out. I implemented this once before and Range reverted it foolishly.

**Comment by kheimerl** [comment]
There's save and read functions, should just be a matter of doing it more often and more efficiently.

**Comment by kheimerl** [comment]
So it turns out that smq _has_ storage but it's broken:
Stores in /tmp/save every minute
Can't read SMS-DELIVER messages, which are the outbound messages you'd want to store.

**Comment by kheimerl** [comment]
Fixed in https://github.com/endaga/smqueue/commit/61414331980d3e2a3ef10fc698ef2944fb0471d5
