### ISSUE TITLE
CDR file at /var/lib/OpenBTS/smq.cdr could not be created or opened

### ISSUE THREAD

**Issue by yosemitebandit** [endaga/smqueue#2]
from syslog on a local box

```
Mar 24 18:12:27 endaga smqueue: ALERT 1110:1147 2015/03/24 18:12:27.5 smqueue.cpp:946:write_cdr: CDR file at /var/lib/OpenBTS/smq.cdr could not be created or opened!
```

**Comment by kheimerl** [comment]
This is because there is no /var/lib/OpenBTS. Just need to change the directory.

**Comment by kheimerl** [comment]
Should be fixed in https://github.com/endaga/smqueue/pull/16

**Comment by kheimerl** [comment]
Fixed in https://github.com/endaga/smqueue/commit/1acf1e2f0f00d3401258686913f4f1134c921bf8
